### ISSUE TITLE
index issue in pre_proj.m

### ISSUE THREAD

**Issue by zexiangliu** [pettni/pcis#1]
https://github.com/pettni/pcis/blob/16cdd1665562114969485c5ffb3df0064dac0ef1/lib/%40Dyn/pre_proj.m#L72

It seems that the above line should be  ```wext_p = dyn.XW_V{iw}(:, dyn.nx+1:dyn.nx+dyn.np); ```, since it enumurates over the vertices of the constraint of the non-measurable disturbance w.

**Comment by pettni** [comment]
Yeah, that's definitely a typo, thanks! Feel free to push a patch and close the issue.

**Comment by zexiangliu** [comment]
closed via changes in 6f88a96
